name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  latex:
    runs-on: ubuntu-latest
    container:
      image: mroynard/latex-maker:latest
    steps:
      -
        name: Build latex
        uses: actions/checkout@v2
        run: make
