name: Continuous Integration
inputs:
  path:
    description: "Path of the directory containing the static assets."
    required: true
    default: "_site/"
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  latex:
    runs-on: ubuntu-latest
    container:
      image: mroynard/latex-maker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build latex
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: thesis-artifacts
          path: |
            roynard.thesis.2022/*.pdf
